Update comment with output of migration

diff --git a/.github/workflows/test-migration.yml b/.github/workflows/test-migration.yml
--- a/.github/workflows/test-migration.yml
+++ b/.github/workflows/test-migration.yml
@@ -54,66 +54,58 @@ jobs:
         cd ./users-api/src
         EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
         OUTPUT=$(npx sequelize db:migrate --env ci 2>&1) || true
+        EXIT_CODE=$?
         echo "MIGRATION_OUTPUT<<$EOF" >> $GITHUB_OUTPUT
         echo "$OUTPUT" >> $GITHUB_OUTPUT
         echo "$EOF" >> $GITHUB_OUTPUT
-        
-        # OUTPUT=$(npx sequelize db:migrate --env ci 2>&1) || true
-        # EXIT_CODE=$?
-        # echo "MIGRATION_OUTPUT=$OUTPUT" >> $GITHUB_OUTPUT
-        # echo "EXIT_CODE=$EXIT_CODE" >> $GITHUB_STATE
+        echo "EXIT_CODE=$EXIT_CODE" >> $GITHUB_OUTPUT
 
     - name: Add or Update Comment on PR
+      uses: actions/github-script@v7
+      if: always() # Ensures this step runs even if the migration step fails
       env:
         MIGRATION_OUTPUT: ${{ steps.migration.outputs.MIGRATION_OUTPUT }}
-      run: |
-        echo "Output: $MIGRATION_OUTPUT"
-      # uses: actions/github-script@v7
-      # if: always() # Ensures this step runs even if the migration step fails
-      # env:
-      #   OUTPUT: ${{ steps.migration.outputs.output }}
-      #   EXIT_CODE: ${{ steps.migration.outputs.exit_code }}
-      
-      # with:
-      #   script: |
-      #     const { OUTPUT, EXIT_CODE } = process.env
-      #     if (!OUTPUT) {
-      #       console.log("no output")
-      #       return
-      #     }
+        EXIT_CODE: ${{ steps.migration.outputs.EXIT_CODE }}
+      with:
+        script: |
+          const { MIGRATION_OUTPUT, EXIT_CODE } = process.env
+          if (!MIGRATION_OUTPUT) {
+            console.log("no output")
+            return
+          }
 
-      #     const migrationMessage = exitCode == 0 ? 'Migration successful' : `Migration failed with exit code ${EXIT_CODE}: ${OUTPUT}`;
-      #     const commentIdentifier = '🔄 Sequelize Migration Result'; // Unique identifier for the comment
-      #     const commentBody = `${commentIdentifier}\n${migrationMessage}`;
+          const migrationMessage = EXIT_CODE == 0 ? 'Migration successful' : `Migration failed with exit code ${EXIT_CODE}: ${MIGRATION_OUTPUT}`;
+          const commentIdentifier = '🔄 Sequelize Migration Result'; // Unique identifier for the comment
+          const commentBody = `${commentIdentifier}\n${migrationMessage}`;
 
-      #     const issue_number = context.issue.number;
-      #     const { owner, repo } = context.repo;
+          const issue_number = context.issue.number;
+          const { owner, repo } = context.repo;
 
-      #     // Find existing comment
-      #     const comments = await github.rest.issues.listComments({
-      #       issue_number,
-      #       owner,
-      #       repo
-      #     });
+          // Find existing comment
+          const comments = await github.rest.issues.listComments({
+            issue_number,
+            owner,
+            repo
+          });
 
-      #     const migrationComment = comments.data.find(comment => comment.body.startsWith(commentIdentifier));
+          const migrationComment = comments.data.find(comment => comment.body.startsWith(commentIdentifier));
 
-      #     // Update existing comment or create a new one
-      #     if (migrationComment) {
-      #       await github.rest.issues.updateComment({
-      #         owner,
-      #         repo,
-      #         comment_id: migrationComment.id,
-      #         body: commentBody
-      #       });
-      #     } else {
-      #       await github.rest.issues.createComment({
-      #         issue_number,
-      #         owner,
-      #         repo,
-      #         body: commentBody
-      #       });
-      #     }
+          // Update existing comment or create a new one
+          if (migrationComment) {
+            await github.rest.issues.updateComment({
+              owner,
+              repo,
+              comment_id: migrationComment.id,
+              body: commentBody
+            });
+          } else {
+            await github.rest.issues.createComment({
+              issue_number,
+              owner,
+              repo,
+              body: commentBody
+            });
+          }
 
     - name: Cleanup
       run: docker stop $DB_HOST
